"""Add status field to Donor model

Revision ID: 114cb63fa8a0
Revises: e6269e6fb9b2
Create Date: 2025-02-06 03:40:56.525437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114cb63fa8a0'
down_revision = 'e6269e6fb9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
