"""Update Patient model with registration fields

Revision ID: e6269e6fb9b2
Revises: c02ab3e2385b
Create Date: 2025-02-06 03:02:30.053922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6269e6fb9b2'
down_revision = 'c02ab3e2385b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blood_request')
    op.drop_table('admins')
    op.drop_table('patient')
    op.drop_table('blood_requests')
    op.drop_table('user')
    op.drop_table('donations')
    op.drop_table('appointments')
    op.drop_table('donation')
    op.drop_table('donor')
    op.drop_table('users')
    op.drop_table('donors')
    op.drop_table('blood_inventory')
    op.drop_table('patients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('blood_type', sa.VARCHAR(length=3), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=20), nullable=False),
    sa.Column('medical_history', sa.TEXT(), nullable=True),
    sa.Column('allergies', sa.TEXT(), nullable=True),
    sa.Column('current_medications', sa.TEXT(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('height', sa.FLOAT(), nullable=True),
    sa.Column('emergency_contact_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('emergency_contact_relation', sa.VARCHAR(length=50), nullable=True),
    sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_transfusion_date', sa.DATETIME(), nullable=True),
    sa.Column('total_transfusions', sa.INTEGER(), nullable=True),
    sa.Column('transfusion_reactions', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_inventory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('blood_type', sa.VARCHAR(length=3), nullable=False),
    sa.Column('quantity_ml', sa.INTEGER(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=False),
    sa.Column('expiry_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('minimum_level', sa.INTEGER(), nullable=True),
    sa.Column('optimal_level', sa.INTEGER(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blood_type')
    )
    op.create_table('donors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('blood_type', sa.VARCHAR(length=3), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=20), nullable=False),
    sa.Column('last_donation_date', sa.DATETIME(), nullable=True),
    sa.Column('total_donations', sa.INTEGER(), nullable=True),
    sa.Column('medical_conditions', sa.TEXT(), nullable=True),
    sa.Column('is_eligible', sa.BOOLEAN(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('height', sa.FLOAT(), nullable=True),
    sa.Column('hemoglobin_level', sa.FLOAT(), nullable=True),
    sa.Column('blood_pressure', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pulse_rate', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('donor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('blood_type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=20), nullable=False),
    sa.Column('last_donation', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('donor_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity_ml', sa.INTEGER(), nullable=False),
    sa.Column('donation_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_date', sa.DATETIME(), nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=200), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('doctor_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), nullable=True),
    sa.Column('room_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.Column('cancellation_reason', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('donor_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity_ml', sa.INTEGER(), nullable=False),
    sa.Column('donation_date', sa.DATETIME(), nullable=False),
    sa.Column('hemoglobin_level', sa.FLOAT(), nullable=True),
    sa.Column('blood_pressure', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pulse_rate', sa.INTEGER(), nullable=True),
    sa.Column('donation_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('screening_passed', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blood_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('blood_type', sa.VARCHAR(length=3), nullable=False),
    sa.Column('quantity_ml', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('urgency_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('request_date', sa.DATETIME(), nullable=False),
    sa.Column('fulfillment_date', sa.DATETIME(), nullable=True),
    sa.Column('diagnosis', sa.VARCHAR(length=200), nullable=True),
    sa.Column('requesting_physician', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('blood_type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), nullable=True),
    sa.Column('access_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('blood_type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('quantity_ml', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('request_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
